store_project/products/urls.py
from django.urls import path

from . import views

app_name = 'products'
urlpatterns = [

	path('', views.ProductList.as_view(), name='product_list'),
    path('<int:pk>', views.ProductDetail.as_view(), name='product_detail'), 

]

store_project/store_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
]

store_project/products/models.py
from django.db import models

class Product(models.Model):
    name = models.CharField(max_length=512)
    price = models.IntegerField()
    description = models.TextField()
   
    def __str__(self):
        return str(self.name)

store_project/products/views.py
from django.shortcuts import render

from django.views.generic import ListView, DetailView


from .models import Product


class ProductList(ListView):
    model = Product
    context_object_name = 'product_list'

class ProductDetail(DetailView):
    model = Product

store_project/products/templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/favicon.ico">

    <title>Simle store</title>

    <!-- Bootstrap core CSS -->
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
  <!--  <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet"> -->

    <!-- Custom styles for this template -->
  <!--   <link href="static/navbar.css" rel="stylesheet"> -->
   
 
    
   <link href="{% static 'navbar.css' %}" rel="stylesheet">
   
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    {% block title %}

    {% endblock %}

  </head>

  <body>

    <div class="container">

      <!-- Static navbar -->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Project name</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#">About</a></li>
              <li><a href="#">Contact</a></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li role="separator" class="divider"></li>
                  <li class="dropdown-header">Nav header</li>
                  <li><a href="#">Separated link</a></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class="active"><a href="./">Default <span class="sr-only">(current)</span></a></li>
              <li><a href="../navbar-static-top/">Static top</a></li>
              <li><a href="../navbar-fixed-top/">Fixed top</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

      <!-- Main component for a primary marketing message or call to action -->
      <div class="jumbotron">
        <h1>Products</h1>

      {% block content %}



      {% endblock %}

      </div>




    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <!--
      <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script> 
    -->
  </body>
</html>

store_project/products/templates/products/product_detail.html
{% extends 'base.html' %}


{% block title %}

	<title> {{ product.name }} </title>

{% endblock %}



{% block content %}
	
	<h3>  {{ product.name }}  </h3>

	<div>

	<p> {{ product.description }}  <p/>
	</div>

	<div>
		<a href="{% url 'products:product_list'  %}"> Back to product list </a>
	</div>

{% endblock %}

store_project/products/templates/products/product_list.html
{% extends 'base.html' %}


{% block title %}

	<title> Products </title>

{% endblock %}



{% block content %}

	
	{% if product_list != None %}
	
		<ul>
			{% for product in product_list %}
				<li>
			         <h3>
				      <a href="{% url 'products:product_detail' product.pk %}"> 
				      	{{ product.name }} 
				      </a>
				   </h3>
				</li>

			{% endfor %}		
		</ul>


	{% else %}
	

		<div class="starter-template">

	        <h1>No items in models</h1>

	        <p class="lead"> <b> Note : </b> to upload data to Product model, use <br> $ python manage.py loaddata fixtures/products.json --app products </p>

	    </div>

     {% endif %}


{% endblock %}